// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirpy.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirpy = `-- name: CreateChirpy :one
INSERT INTO chirpy (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(), -- id
    NOW(),             -- created_at
    NOW(),             -- updated_at
    $1,                 -- body
    $2                 -- user_id
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpyParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirpy(ctx context.Context, arg CreateChirpyParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirpy, arg.Body, arg.UserID)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteAllChirpy = `-- name: DeleteAllChirpy :exec
DELETE FROM chirpy
`

func (q *Queries) DeleteAllChirpy(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirpy)
	return err
}

const deleteChirpyByID = `-- name: DeleteChirpyByID :exec

DELETE FROM chirpy
WHERE id = $1 AND user_id = $2
`

type DeleteChirpyByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// -- name DeleteChirpyByID :one
// DELETE FROM chirpy
// WHERE id = $1 AND user_id = $2;
func (q *Queries) DeleteChirpyByID(ctx context.Context, arg DeleteChirpyByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirpyByID, arg.ID, arg.UserID)
	return err
}

const getChirpyByID = `-- name: GetChirpyByID :one
SELECT id, created_at, updated_at, body, user_id FROM chirpy
WHERE id = $1
`

func (q *Queries) GetChirpyByID(ctx context.Context, id uuid.UUID) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, getChirpyByID, id)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const listChirpy = `-- name: ListChirpy :many
SELECT id, created_at, updated_at, body, user_id FROM chirpy
ORDER BY created_at ASC
`

func (q *Queries) ListChirpy(ctx context.Context) ([]Chirpy, error) {
	rows, err := q.db.QueryContext(ctx, listChirpy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirpy
	for rows.Next() {
		var i Chirpy
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
